package com.mas.rave.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.mas.rave.main.vo.Operation;
import com.mas.rave.main.vo.OperationExample;

public interface OperationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation
     *
     * @mbggenerated Tue Dec 20 22:34:55 CST 2011
     */
    int countByExample(OperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation
     *
     * @mbggenerated Tue Dec 20 22:34:55 CST 2011
     */
    int deleteByExample(OperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation
     *
     * @mbggenerated Tue Dec 20 22:34:55 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation
     *
     * @mbggenerated Tue Dec 20 22:34:55 CST 2011
     */
    int insert(Operation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation
     *
     * @mbggenerated Tue Dec 20 22:34:55 CST 2011
     */
    int insertSelective(Operation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation
     *
     * @mbggenerated Tue Dec 20 22:34:55 CST 2011
     */
    List<Operation> selectByExample(OperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation
     *
     * @mbggenerated Tue Dec 20 22:34:55 CST 2011
     */
    Operation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation
     *
     * @mbggenerated Tue Dec 20 22:34:55 CST 2011
     */
    int updateByExampleSelective(@Param("record") Operation record, @Param("example") OperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation
     *
     * @mbggenerated Tue Dec 20 22:34:55 CST 2011
     */
    int updateByExample(@Param("record") Operation record, @Param("example") OperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation
     *
     * @mbggenerated Tue Dec 20 22:34:55 CST 2011
     */
    int updateByPrimaryKeySelective(Operation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation
     *
     * @mbggenerated Tue Dec 20 22:34:55 CST 2011
     */
    int updateByPrimaryKey(Operation record);
}