
package com.hykj.gamecenter.protocol;

// Generated by the protocol buffer compiler.  DO NOT EDIT!

@SuppressWarnings("hiding")
public interface Packet {

    // enum MaskCode
    public static final int DEFAULT = 0;
    public static final int PARAMS_GZIP = 1;
    public static final int PARAMS_RSA = 2;

    public static final class ReqPacket extends
            com.google.protobuf.nano.MessageNano {

        private static volatile ReqPacket[] _emptyArray;

        public static ReqPacket[] emptyArray() {
            // Lazily initializes the empty array
            if (_emptyArray == null) {
                synchronized (com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
                    if (_emptyArray == null) {
                        _emptyArray = new ReqPacket[0];
                    }
                }
            }
            return _emptyArray;
        }

        // required int32 mask = 1;
        public int mask;

        // required string udi = 2;
        public java.lang.String udi;

        // repeated string action = 3;
        public java.lang.String[] action;

        // repeated bytes params = 4;
        public byte[][] params;

        // required int32 reqNo = 5;
        public int reqNo;

        // optional int32 chnNo = 6;
        public int chnNo;

        // optional int32 chnPos = 7;
        public int chnPos;

        // required int32 clientId = 8;
        public int clientId;

        // optional int32 clientPos = 9;
        public int clientPos;

        // optional string clientVer = 10;
        public java.lang.String clientVer;

        // optional string rsaKeyVer = 11;
        public java.lang.String rsaKeyVer;

        public ReqPacket() {
            clear();
        }

        public ReqPacket clear() {
            mask = 0;
            udi = "";
            action = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
            params = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES_ARRAY;
            reqNo = 0;
            chnNo = 0;
            chnPos = 0;
            clientId = 0;
            clientPos = 0;
            clientVer = "";
            rsaKeyVer = "";
            cachedSize = -1;
            return this;
        }

        @Override
        public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
                throws java.io.IOException {
            output.writeInt32(1, this.mask);
            output.writeString(2, this.udi);
            if (this.action != null && this.action.length > 0) {
                for (int i = 0; i < this.action.length; i++) {
                    java.lang.String element = this.action[i];
                    if (element != null) {
                        output.writeString(3, element);
                    }
                }
            }
            if (this.params != null && this.params.length > 0) {
                for (int i = 0; i < this.params.length; i++) {
                    byte[] element = this.params[i];
                    if (element != null) {
                        output.writeBytes(4, element);
                    }
                }
            }
            output.writeInt32(5, this.reqNo);
            if (this.chnNo != 0) {
                output.writeInt32(6, this.chnNo);
            }
            if (this.chnPos != 0) {
                output.writeInt32(7, this.chnPos);
            }
            output.writeInt32(8, this.clientId);
            if (this.clientPos != 0) {
                output.writeInt32(9, this.clientPos);
            }
            if (!this.clientVer.equals("")) {
                output.writeString(10, this.clientVer);
            }
            if (!this.rsaKeyVer.equals("")) {
                output.writeString(11, this.rsaKeyVer);
            }
            super.writeTo(output);
        }

        @Override
        protected int computeSerializedSize() {
            int size = super.computeSerializedSize();
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
                    .computeInt32Size(1, this.mask);
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
                    .computeStringSize(2, this.udi);
            if (this.action != null && this.action.length > 0) {
                int dataCount = 0;
                int dataSize = 0;
                for (int i = 0; i < this.action.length; i++) {
                    java.lang.String element = this.action[i];
                    if (element != null) {
                        dataCount++;
                        dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                                .computeStringSizeNoTag(element);
                    }
                }
                size += dataSize;
                size += 1 * dataCount;
            }
            if (this.params != null && this.params.length > 0) {
                int dataCount = 0;
                int dataSize = 0;
                for (int i = 0; i < this.params.length; i++) {
                    byte[] element = this.params[i];
                    if (element != null) {
                        dataCount++;
                        dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                                .computeBytesSizeNoTag(element);
                    }
                }
                size += dataSize;
                size += 1 * dataCount;
            }
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
                    .computeInt32Size(5, this.reqNo);
            if (this.chnNo != 0) {
                size += com.google.protobuf.nano.CodedOutputByteBufferNano
                        .computeInt32Size(6, this.chnNo);
            }
            if (this.chnPos != 0) {
                size += com.google.protobuf.nano.CodedOutputByteBufferNano
                        .computeInt32Size(7, this.chnPos);
            }
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
                    .computeInt32Size(8, this.clientId);
            if (this.clientPos != 0) {
                size += com.google.protobuf.nano.CodedOutputByteBufferNano
                        .computeInt32Size(9, this.clientPos);
            }
            if (!this.clientVer.equals("")) {
                size += com.google.protobuf.nano.CodedOutputByteBufferNano
                        .computeStringSize(10, this.clientVer);
            }
            if (!this.rsaKeyVer.equals("")) {
                size += com.google.protobuf.nano.CodedOutputByteBufferNano
                        .computeStringSize(11, this.rsaKeyVer);
            }
            return size;
        }

        @Override
        public ReqPacket mergeFrom(
                com.google.protobuf.nano.CodedInputByteBufferNano input)
                throws java.io.IOException {
            while (true) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        return this;
                    default: {
                        if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                            return this;
                        }
                        break;
                    }
                    case 8: {
                        this.mask = input.readInt32();
                        break;
                    }
                    case 18: {
                        this.udi = input.readString();
                        break;
                    }
                    case 26: {
                        int arrayLength = com.google.protobuf.nano.WireFormatNano
                                .getRepeatedFieldArrayLength(input, 26);
                        int i = this.action == null ? 0 : this.action.length;
                        java.lang.String[] newArray = new java.lang.String[i + arrayLength];
                        if (i != 0) {
                            java.lang.System.arraycopy(this.action, 0, newArray, 0, i);
                        }
                        for (; i < newArray.length - 1; i++) {
                            newArray[i] = input.readString();
                            input.readTag();
                        }
                        // Last one without readTag.
                        newArray[i] = input.readString();
                        this.action = newArray;
                        break;
                    }
                    case 34: {
                        int arrayLength = com.google.protobuf.nano.WireFormatNano
                                .getRepeatedFieldArrayLength(input, 34);
                        int i = this.params == null ? 0 : this.params.length;
                        byte[][] newArray = new byte[i + arrayLength][];
                        if (i != 0) {
                            java.lang.System.arraycopy(this.params, 0, newArray, 0, i);
                        }
                        for (; i < newArray.length - 1; i++) {
                            newArray[i] = input.readBytes();
                            input.readTag();
                        }
                        // Last one without readTag.
                        newArray[i] = input.readBytes();
                        this.params = newArray;
                        break;
                    }
                    case 40: {
                        this.reqNo = input.readInt32();
                        break;
                    }
                    case 48: {
                        this.chnNo = input.readInt32();
                        break;
                    }
                    case 56: {
                        this.chnPos = input.readInt32();
                        break;
                    }
                    case 64: {
                        this.clientId = input.readInt32();
                        break;
                    }
                    case 72: {
                        this.clientPos = input.readInt32();
                        break;
                    }
                    case 82: {
                        this.clientVer = input.readString();
                        break;
                    }
                    case 90: {
                        this.rsaKeyVer = input.readString();
                        break;
                    }
                }
            }
        }

        public static ReqPacket parseFrom(byte[] data)
                throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
            return com.google.protobuf.nano.MessageNano.mergeFrom(new ReqPacket(), data);
        }

        public static ReqPacket parseFrom(
                com.google.protobuf.nano.CodedInputByteBufferNano input)
                throws java.io.IOException {
            return new ReqPacket().mergeFrom(input);
        }
    }

    public static final class RspPacket extends
            com.google.protobuf.nano.MessageNano {

        private static volatile RspPacket[] _emptyArray;

        public static RspPacket[] emptyArray() {
            // Lazily initializes the empty array
            if (_emptyArray == null) {
                synchronized (com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
                    if (_emptyArray == null) {
                        _emptyArray = new RspPacket[0];
                    }
                }
            }
            return _emptyArray;
        }

        // required int32 mask = 1;
        public int mask;

        // required int32 rescode = 2;
        public int rescode;

        // required string resmsg = 3;
        public java.lang.String resmsg;

        // repeated string action = 4;
        public java.lang.String[] action;

        // repeated bytes params = 5;
        public byte[][] params;

        public RspPacket() {
            clear();
        }

        public RspPacket clear() {
            mask = 0;
            rescode = 0;
            resmsg = "";
            action = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
            params = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES_ARRAY;
            cachedSize = -1;
            return this;
        }

        @Override
        public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
                throws java.io.IOException {
            output.writeInt32(1, this.mask);
            output.writeInt32(2, this.rescode);
            output.writeString(3, this.resmsg);
            if (this.action != null && this.action.length > 0) {
                for (int i = 0; i < this.action.length; i++) {
                    java.lang.String element = this.action[i];
                    if (element != null) {
                        output.writeString(4, element);
                    }
                }
            }
            if (this.params != null && this.params.length > 0) {
                for (int i = 0; i < this.params.length; i++) {
                    byte[] element = this.params[i];
                    if (element != null) {
                        output.writeBytes(5, element);
                    }
                }
            }
            super.writeTo(output);
        }

        @Override
        protected int computeSerializedSize() {
            int size = super.computeSerializedSize();
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
                    .computeInt32Size(1, this.mask);
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
                    .computeInt32Size(2, this.rescode);
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
                    .computeStringSize(3, this.resmsg);
            if (this.action != null && this.action.length > 0) {
                int dataCount = 0;
                int dataSize = 0;
                for (int i = 0; i < this.action.length; i++) {
                    java.lang.String element = this.action[i];
                    if (element != null) {
                        dataCount++;
                        dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                                .computeStringSizeNoTag(element);
                    }
                }
                size += dataSize;
                size += 1 * dataCount;
            }
            if (this.params != null && this.params.length > 0) {
                int dataCount = 0;
                int dataSize = 0;
                for (int i = 0; i < this.params.length; i++) {
                    byte[] element = this.params[i];
                    if (element != null) {
                        dataCount++;
                        dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                                .computeBytesSizeNoTag(element);
                    }
                }
                size += dataSize;
                size += 1 * dataCount;
            }
            return size;
        }

        @Override
        public RspPacket mergeFrom(
                com.google.protobuf.nano.CodedInputByteBufferNano input)
                throws java.io.IOException {
            while (true) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        return this;
                    default: {
                        if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                            return this;
                        }
                        break;
                    }
                    case 8: {
                        this.mask = input.readInt32();
                        break;
                    }
                    case 16: {
                        this.rescode = input.readInt32();
                        break;
                    }
                    case 26: {
                        this.resmsg = input.readString();
                        break;
                    }
                    case 34: {
                        int arrayLength = com.google.protobuf.nano.WireFormatNano
                                .getRepeatedFieldArrayLength(input, 34);
                        int i = this.action == null ? 0 : this.action.length;
                        java.lang.String[] newArray = new java.lang.String[i + arrayLength];
                        if (i != 0) {
                            java.lang.System.arraycopy(this.action, 0, newArray, 0, i);
                        }
                        for (; i < newArray.length - 1; i++) {
                            newArray[i] = input.readString();
                            input.readTag();
                        }
                        // Last one without readTag.
                        newArray[i] = input.readString();
                        this.action = newArray;
                        break;
                    }
                    case 42: {
                        int arrayLength = com.google.protobuf.nano.WireFormatNano
                                .getRepeatedFieldArrayLength(input, 42);
                        int i = this.params == null ? 0 : this.params.length;
                        byte[][] newArray = new byte[i + arrayLength][];
                        if (i != 0) {
                            java.lang.System.arraycopy(this.params, 0, newArray, 0, i);
                        }
                        for (; i < newArray.length - 1; i++) {
                            newArray[i] = input.readBytes();
                            input.readTag();
                        }
                        // Last one without readTag.
                        newArray[i] = input.readBytes();
                        this.params = newArray;
                        break;
                    }
                }
            }
        }

        public static RspPacket parseFrom(byte[] data)
                throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
            return com.google.protobuf.nano.MessageNano.mergeFrom(new RspPacket(), data);
        }

        public static RspPacket parseFrom(
                com.google.protobuf.nano.CodedInputByteBufferNano input)
                throws java.io.IOException {
            return new RspPacket().mergeFrom(input);
        }
    }

    public static final class RspRsaKey extends
            com.google.protobuf.nano.MessageNano {

        private static volatile RspRsaKey[] _emptyArray;

        public static RspRsaKey[] emptyArray() {
            // Lazily initializes the empty array
            if (_emptyArray == null) {
                synchronized (com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
                    if (_emptyArray == null) {
                        _emptyArray = new RspRsaKey[0];
                    }
                }
            }
            return _emptyArray;
        }

        // required string rsaVer = 1;
        public java.lang.String rsaVer;

        // required string rsaKey = 2;
        public java.lang.String rsaKey;

        public RspRsaKey() {
            clear();
        }

        public RspRsaKey clear() {
            rsaVer = "";
            rsaKey = "";
            cachedSize = -1;
            return this;
        }

        @Override
        public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
                throws java.io.IOException {
            output.writeString(1, this.rsaVer);
            output.writeString(2, this.rsaKey);
            super.writeTo(output);
        }

        @Override
        protected int computeSerializedSize() {
            int size = super.computeSerializedSize();
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
                    .computeStringSize(1, this.rsaVer);
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
                    .computeStringSize(2, this.rsaKey);
            return size;
        }

        @Override
        public RspRsaKey mergeFrom(
                com.google.protobuf.nano.CodedInputByteBufferNano input)
                throws java.io.IOException {
            while (true) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        return this;
                    default: {
                        if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                            return this;
                        }
                        break;
                    }
                    case 10: {
                        this.rsaVer = input.readString();
                        break;
                    }
                    case 18: {
                        this.rsaKey = input.readString();
                        break;
                    }
                }
            }
        }

        public static RspRsaKey parseFrom(byte[] data)
                throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
            return com.google.protobuf.nano.MessageNano.mergeFrom(new RspRsaKey(), data);
        }

        public static RspRsaKey parseFrom(
                com.google.protobuf.nano.CodedInputByteBufferNano input)
                throws java.io.IOException {
            return new RspRsaKey().mergeFrom(input);
        }
    }
}
