// Generated by the protocol buffer compiler.  DO NOT EDIT!
package com.hykj.gamecenter.protocol;

@SuppressWarnings("hiding")
public interface UAC {

  public static final class AccountInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AccountInfo[] _emptyArray;
    public static AccountInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AccountInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // required string openId = 1;
    public java.lang.String openId;

    // required string token = 2;
    public java.lang.String token;

    // optional string mobile = 3;
    public java.lang.String mobile;

    // optional string userName = 4;
    public java.lang.String userName;

    // optional int32 status = 5;
    public int status;

    // optional string regTime = 6;
    public java.lang.String regTime;

    // optional int32 pwdStatus = 7;
    public int pwdStatus;

    // optional string nickName = 8;
    public java.lang.String nickName;

    // optional string headImgUrl = 9;
    public java.lang.String headImgUrl;

    public AccountInfo() {
      clear();
    }

    public AccountInfo clear() {
      openId = "";
      token = "";
      mobile = "";
      userName = "";
      status = 0;
      regTime = "";
      pwdStatus = 0;
      nickName = "";
      headImgUrl = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeString(1, this.openId);
      output.writeString(2, this.token);
      if (!this.mobile.equals("")) {
        output.writeString(3, this.mobile);
      }
      if (!this.userName.equals("")) {
        output.writeString(4, this.userName);
      }
      if (this.status != 0) {
        output.writeInt32(5, this.status);
      }
      if (!this.regTime.equals("")) {
        output.writeString(6, this.regTime);
      }
      if (this.pwdStatus != 0) {
        output.writeInt32(7, this.pwdStatus);
      }
      if (!this.nickName.equals("")) {
        output.writeString(8, this.nickName);
      }
      if (!this.headImgUrl.equals("")) {
        output.writeString(9, this.headImgUrl);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.openId);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.token);
      if (!this.mobile.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.mobile);
      }
      if (!this.userName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.userName);
      }
      if (this.status != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.status);
      }
      if (!this.regTime.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.regTime);
      }
      if (this.pwdStatus != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(7, this.pwdStatus);
      }
      if (!this.nickName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.nickName);
      }
      if (!this.headImgUrl.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(9, this.headImgUrl);
      }
      return size;
    }

    @Override
    public AccountInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.openId = input.readString();
            break;
          }
          case 18: {
            this.token = input.readString();
            break;
          }
          case 26: {
            this.mobile = input.readString();
            break;
          }
          case 34: {
            this.userName = input.readString();
            break;
          }
          case 40: {
            this.status = input.readInt32();
            break;
          }
          case 50: {
            this.regTime = input.readString();
            break;
          }
          case 56: {
            this.pwdStatus = input.readInt32();
            break;
          }
          case 66: {
            this.nickName = input.readString();
            break;
          }
          case 74: {
            this.headImgUrl = input.readString();
            break;
          }
        }
      }
    }

    public static AccountInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AccountInfo(), data);
    }

    public static AccountInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AccountInfo().mergeFrom(input);
    }
  }

  public static final class QueryAction extends
      com.google.protobuf.nano.MessageNano {

    private static volatile QueryAction[] _emptyArray;
    public static QueryAction[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new QueryAction[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string name = 1;
    public java.lang.String name;

    // required string type = 2;
    public java.lang.String type;

    // required string flag = 3;
    public java.lang.String flag;

    // required string paramValue = 4;
    public java.lang.String paramValue;

    public QueryAction() {
      clear();
    }

    public QueryAction clear() {
      name = "";
      type = "";
      flag = "";
      paramValue = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.name.equals("")) {
        output.writeString(1, this.name);
      }
      output.writeString(2, this.type);
      output.writeString(3, this.flag);
      output.writeString(4, this.paramValue);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.name.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.name);
      }
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.type);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(3, this.flag);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(4, this.paramValue);
      return size;
    }

    @Override
    public QueryAction mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.name = input.readString();
            break;
          }
          case 18: {
            this.type = input.readString();
            break;
          }
          case 26: {
            this.flag = input.readString();
            break;
          }
          case 34: {
            this.paramValue = input.readString();
            break;
          }
        }
      }
    }

    public static QueryAction parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new QueryAction(), data);
    }

    public static QueryAction parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new QueryAction().mergeFrom(input);
    }
  }

  public static final class QueryConfigInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile QueryConfigInfo[] _emptyArray;
    public static QueryConfigInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new QueryConfigInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // required string picUrl = 1;
    public java.lang.String picUrl;

    // required string configName = 2;
    public java.lang.String configName;

    // required .QueryAction action = 3;
    public UAC.QueryAction action;

    public QueryConfigInfo() {
      clear();
    }

    public QueryConfigInfo clear() {
      picUrl = "";
      configName = "";
      action = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeString(1, this.picUrl);
      output.writeString(2, this.configName);
      if (this.action != null) {
        output.writeMessage(3, this.action);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.picUrl);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.configName);
      if (this.action != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.action);
      }
      return size;
    }

    @Override
    public QueryConfigInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.picUrl = input.readString();
            break;
          }
          case 18: {
            this.configName = input.readString();
            break;
          }
          case 26: {
            if (this.action == null) {
              this.action = new UAC.QueryAction();
            }
            input.readMessage(this.action);
            break;
          }
        }
      }
    }

    public static QueryConfigInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new QueryConfigInfo(), data);
    }

    public static QueryConfigInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new QueryConfigInfo().mergeFrom(input);
    }
  }

  public static final class ReqOpenId extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ReqOpenId[] _emptyArray;
    public static ReqOpenId[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ReqOpenId[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string openId = 1;
    public java.lang.String openId;

    // optional string token = 2;
    public java.lang.String token;

    public ReqOpenId() {
      clear();
    }

    public ReqOpenId clear() {
      openId = "";
      token = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.openId.equals("")) {
        output.writeString(1, this.openId);
      }
      if (!this.token.equals("")) {
        output.writeString(2, this.token);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.openId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.openId);
      }
      if (!this.token.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.token);
      }
      return size;
    }

    @Override
    public ReqOpenId mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.openId = input.readString();
            break;
          }
          case 18: {
            this.token = input.readString();
            break;
          }
        }
      }
    }

    public static ReqOpenId parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ReqOpenId(), data);
    }

    public static ReqOpenId parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ReqOpenId().mergeFrom(input);
    }
  }

  public static final class RspOpenId extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RspOpenId[] _emptyArray;
    public static RspOpenId[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RspOpenId[0];
          }
        }
      }
      return _emptyArray;
    }

    // required int32 rescode = 1;
    public int rescode;

    // required string resmsg = 2;
    public java.lang.String resmsg;

    // optional .AccountInfo account = 3;
    public UAC.AccountInfo account;

    public RspOpenId() {
      clear();
    }

    public RspOpenId clear() {
      rescode = 0;
      resmsg = "";
      account = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeInt32(1, this.rescode);
      output.writeString(2, this.resmsg);
      if (this.account != null) {
        output.writeMessage(3, this.account);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.rescode);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.resmsg);
      if (this.account != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.account);
      }
      return size;
    }

    @Override
    public RspOpenId mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.rescode = input.readInt32();
            break;
          }
          case 18: {
            this.resmsg = input.readString();
            break;
          }
          case 26: {
            if (this.account == null) {
              this.account = new UAC.AccountInfo();
            }
            input.readMessage(this.account);
            break;
          }
        }
      }
    }

    public static RspOpenId parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RspOpenId(), data);
    }

    public static RspOpenId parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RspOpenId().mergeFrom(input);
    }
  }

  public static final class ReqBind extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ReqBind[] _emptyArray;
    public static ReqBind[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ReqBind[0];
          }
        }
      }
      return _emptyArray;
    }

    // required string mobile = 1;
    public java.lang.String mobile;

    // required string verCode = 2;
    public java.lang.String verCode;

    // required string openId = 3;
    public java.lang.String openId;

    // optional int32 source = 4;
    public int source;

    public ReqBind() {
      clear();
    }

    public ReqBind clear() {
      mobile = "";
      verCode = "";
      openId = "";
      source = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeString(1, this.mobile);
      output.writeString(2, this.verCode);
      output.writeString(3, this.openId);
      if (this.source != 0) {
        output.writeInt32(4, this.source);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.mobile);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.verCode);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(3, this.openId);
      if (this.source != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.source);
      }
      return size;
    }

    @Override
    public ReqBind mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.mobile = input.readString();
            break;
          }
          case 18: {
            this.verCode = input.readString();
            break;
          }
          case 26: {
            this.openId = input.readString();
            break;
          }
          case 32: {
            this.source = input.readInt32();
            break;
          }
        }
      }
    }

    public static ReqBind parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ReqBind(), data);
    }

    public static ReqBind parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ReqBind().mergeFrom(input);
    }
  }

  public static final class RspBind extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RspBind[] _emptyArray;
    public static RspBind[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RspBind[0];
          }
        }
      }
      return _emptyArray;
    }

    // required int32 rescode = 1;
    public int rescode;

    // required string resmsg = 2;
    public java.lang.String resmsg;

    // optional .AccountInfo account = 3;
    public UAC.AccountInfo account;

    public RspBind() {
      clear();
    }

    public RspBind clear() {
      rescode = 0;
      resmsg = "";
      account = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeInt32(1, this.rescode);
      output.writeString(2, this.resmsg);
      if (this.account != null) {
        output.writeMessage(3, this.account);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.rescode);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.resmsg);
      if (this.account != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.account);
      }
      return size;
    }

    @Override
    public RspBind mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.rescode = input.readInt32();
            break;
          }
          case 18: {
            this.resmsg = input.readString();
            break;
          }
          case 26: {
            if (this.account == null) {
              this.account = new UAC.AccountInfo();
            }
            input.readMessage(this.account);
            break;
          }
        }
      }
    }

    public static RspBind parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RspBind(), data);
    }

    public static RspBind parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RspBind().mergeFrom(input);
    }
  }

  public static final class ReqValidate extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ReqValidate[] _emptyArray;
    public static ReqValidate[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ReqValidate[0];
          }
        }
      }
      return _emptyArray;
    }

    // required string mobile = 1;
    public java.lang.String mobile;

    // required string openId = 2;
    public java.lang.String openId;

    public ReqValidate() {
      clear();
    }

    public ReqValidate clear() {
      mobile = "";
      openId = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeString(1, this.mobile);
      output.writeString(2, this.openId);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.mobile);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.openId);
      return size;
    }

    @Override
    public ReqValidate mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.mobile = input.readString();
            break;
          }
          case 18: {
            this.openId = input.readString();
            break;
          }
        }
      }
    }

    public static ReqValidate parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ReqValidate(), data);
    }

    public static ReqValidate parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ReqValidate().mergeFrom(input);
    }
  }

  public static final class RspValidate extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RspValidate[] _emptyArray;
    public static RspValidate[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RspValidate[0];
          }
        }
      }
      return _emptyArray;
    }

    // required int32 rescode = 1;
    public int rescode;

    // required string resmsg = 2;
    public java.lang.String resmsg;

    public RspValidate() {
      clear();
    }

    public RspValidate clear() {
      rescode = 0;
      resmsg = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeInt32(1, this.rescode);
      output.writeString(2, this.resmsg);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.rescode);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.resmsg);
      return size;
    }

    @Override
    public RspValidate mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.rescode = input.readInt32();
            break;
          }
          case 18: {
            this.resmsg = input.readString();
            break;
          }
        }
      }
    }

    public static RspValidate parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RspValidate(), data);
    }

    public static RspValidate parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RspValidate().mergeFrom(input);
    }
  }

  public static final class ReqQueryConfig extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ReqQueryConfig[] _emptyArray;
    public static ReqQueryConfig[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ReqQueryConfig[0];
          }
        }
      }
      return _emptyArray;
    }

    // required string openId = 1;
    public java.lang.String openId;

    public ReqQueryConfig() {
      clear();
    }

    public ReqQueryConfig clear() {
      openId = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeString(1, this.openId);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.openId);
      return size;
    }

    @Override
    public ReqQueryConfig mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.openId = input.readString();
            break;
          }
        }
      }
    }

    public static ReqQueryConfig parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ReqQueryConfig(), data);
    }

    public static ReqQueryConfig parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ReqQueryConfig().mergeFrom(input);
    }
  }

  public static final class RspQueryConfig extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RspQueryConfig[] _emptyArray;
    public static RspQueryConfig[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RspQueryConfig[0];
          }
        }
      }
      return _emptyArray;
    }

    // required int32 rescode = 1;
    public int rescode;

    // required string resmsg = 2;
    public java.lang.String resmsg;

    // repeated .QueryConfigInfo queryConfig = 3;
    public UAC.QueryConfigInfo[] queryConfig;

    public RspQueryConfig() {
      clear();
    }

    public RspQueryConfig clear() {
      rescode = 0;
      resmsg = "";
      queryConfig = UAC.QueryConfigInfo.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeInt32(1, this.rescode);
      output.writeString(2, this.resmsg);
      if (this.queryConfig != null && this.queryConfig.length > 0) {
        for (int i = 0; i < this.queryConfig.length; i++) {
          UAC.QueryConfigInfo element = this.queryConfig[i];
          if (element != null) {
            output.writeMessage(3, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.rescode);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.resmsg);
      if (this.queryConfig != null && this.queryConfig.length > 0) {
        for (int i = 0; i < this.queryConfig.length; i++) {
          UAC.QueryConfigInfo element = this.queryConfig[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(3, element);
          }
        }
      }
      return size;
    }

    @Override
    public RspQueryConfig mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.rescode = input.readInt32();
            break;
          }
          case 18: {
            this.resmsg = input.readString();
            break;
          }
          case 26: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 26);
            int i = this.queryConfig == null ? 0 : this.queryConfig.length;
            UAC.QueryConfigInfo[] newArray =
                new UAC.QueryConfigInfo[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.queryConfig, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new UAC.QueryConfigInfo();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new UAC.QueryConfigInfo();
            input.readMessage(newArray[i]);
            this.queryConfig = newArray;
            break;
          }
        }
      }
    }

    public static RspQueryConfig parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RspQueryConfig(), data);
    }

    public static RspQueryConfig parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RspQueryConfig().mergeFrom(input);
    }
  }

  public static final class ReqLogin extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ReqLogin[] _emptyArray;
    public static ReqLogin[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ReqLogin[0];
          }
        }
      }
      return _emptyArray;
    }

    // required string userName = 1;
    public java.lang.String userName;

    // required string userPwd = 2;
    public java.lang.String userPwd;

    public ReqLogin() {
      clear();
    }

    public ReqLogin clear() {
      userName = "";
      userPwd = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeString(1, this.userName);
      output.writeString(2, this.userPwd);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.userName);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.userPwd);
      return size;
    }

    @Override
    public ReqLogin mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.userName = input.readString();
            break;
          }
          case 18: {
            this.userPwd = input.readString();
            break;
          }
        }
      }
    }

    public static ReqLogin parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ReqLogin(), data);
    }

    public static ReqLogin parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ReqLogin().mergeFrom(input);
    }
  }

  public static final class RspLogin extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RspLogin[] _emptyArray;
    public static RspLogin[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RspLogin[0];
          }
        }
      }
      return _emptyArray;
    }

    // required int32 rescode = 1;
    public int rescode;

    // required string resmsg = 2;
    public java.lang.String resmsg;

    // optional .AccountInfo account = 3;
    public UAC.AccountInfo account;

    public RspLogin() {
      clear();
    }

    public RspLogin clear() {
      rescode = 0;
      resmsg = "";
      account = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeInt32(1, this.rescode);
      output.writeString(2, this.resmsg);
      if (this.account != null) {
        output.writeMessage(3, this.account);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.rescode);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.resmsg);
      if (this.account != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.account);
      }
      return size;
    }

    @Override
    public RspLogin mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.rescode = input.readInt32();
            break;
          }
          case 18: {
            this.resmsg = input.readString();
            break;
          }
          case 26: {
            if (this.account == null) {
              this.account = new UAC.AccountInfo();
            }
            input.readMessage(this.account);
            break;
          }
        }
      }
    }

    public static RspLogin parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RspLogin(), data);
    }

    public static RspLogin parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RspLogin().mergeFrom(input);
    }
  }

  public static final class ReqUser extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ReqUser[] _emptyArray;
    public static ReqUser[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ReqUser[0];
          }
        }
      }
      return _emptyArray;
    }

    // required string openId = 1;
    public java.lang.String openId;

    // required string token = 2;
    public java.lang.String token;

    public ReqUser() {
      clear();
    }

    public ReqUser clear() {
      openId = "";
      token = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeString(1, this.openId);
      output.writeString(2, this.token);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.openId);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.token);
      return size;
    }

    @Override
    public ReqUser mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.openId = input.readString();
            break;
          }
          case 18: {
            this.token = input.readString();
            break;
          }
        }
      }
    }

    public static ReqUser parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ReqUser(), data);
    }

    public static ReqUser parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ReqUser().mergeFrom(input);
    }
  }

  public static final class RspUser extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RspUser[] _emptyArray;
    public static RspUser[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RspUser[0];
          }
        }
      }
      return _emptyArray;
    }

    // required int32 rescode = 1;
    public int rescode;

    // required string resmsg = 2;
    public java.lang.String resmsg;

    // optional .AccountInfo account = 3;
    public UAC.AccountInfo account;

    public RspUser() {
      clear();
    }

    public RspUser clear() {
      rescode = 0;
      resmsg = "";
      account = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeInt32(1, this.rescode);
      output.writeString(2, this.resmsg);
      if (this.account != null) {
        output.writeMessage(3, this.account);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.rescode);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.resmsg);
      if (this.account != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.account);
      }
      return size;
    }

    @Override
    public RspUser mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.rescode = input.readInt32();
            break;
          }
          case 18: {
            this.resmsg = input.readString();
            break;
          }
          case 26: {
            if (this.account == null) {
              this.account = new UAC.AccountInfo();
            }
            input.readMessage(this.account);
            break;
          }
        }
      }
    }

    public static RspUser parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RspUser(), data);
    }

    public static RspUser parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RspUser().mergeFrom(input);
    }
  }

  public static final class ReqSetUserName extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ReqSetUserName[] _emptyArray;
    public static ReqSetUserName[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ReqSetUserName[0];
          }
        }
      }
      return _emptyArray;
    }

    // required string openId = 1;
    public java.lang.String openId;

    // required string token = 2;
    public java.lang.String token;

    // required string userName = 3;
    public java.lang.String userName;

    public ReqSetUserName() {
      clear();
    }

    public ReqSetUserName clear() {
      openId = "";
      token = "";
      userName = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeString(1, this.openId);
      output.writeString(2, this.token);
      output.writeString(3, this.userName);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.openId);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.token);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(3, this.userName);
      return size;
    }

    @Override
    public ReqSetUserName mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.openId = input.readString();
            break;
          }
          case 18: {
            this.token = input.readString();
            break;
          }
          case 26: {
            this.userName = input.readString();
            break;
          }
        }
      }
    }

    public static ReqSetUserName parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ReqSetUserName(), data);
    }

    public static ReqSetUserName parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ReqSetUserName().mergeFrom(input);
    }
  }

  public static final class RspSetUserName extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RspSetUserName[] _emptyArray;
    public static RspSetUserName[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RspSetUserName[0];
          }
        }
      }
      return _emptyArray;
    }

    // required int32 rescode = 1;
    public int rescode;

    // required string resmsg = 2;
    public java.lang.String resmsg;

    public RspSetUserName() {
      clear();
    }

    public RspSetUserName clear() {
      rescode = 0;
      resmsg = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeInt32(1, this.rescode);
      output.writeString(2, this.resmsg);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.rescode);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.resmsg);
      return size;
    }

    @Override
    public RspSetUserName mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.rescode = input.readInt32();
            break;
          }
          case 18: {
            this.resmsg = input.readString();
            break;
          }
        }
      }
    }

    public static RspSetUserName parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RspSetUserName(), data);
    }

    public static RspSetUserName parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RspSetUserName().mergeFrom(input);
    }
  }

  public static final class ReqSetPwd extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ReqSetPwd[] _emptyArray;
    public static ReqSetPwd[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ReqSetPwd[0];
          }
        }
      }
      return _emptyArray;
    }

    // required string openId = 1;
    public java.lang.String openId;

    // required string token = 2;
    public java.lang.String token;

    // required string newPwd = 3;
    public java.lang.String newPwd;

    // optional string oldPwd = 4;
    public java.lang.String oldPwd;

    public ReqSetPwd() {
      clear();
    }

    public ReqSetPwd clear() {
      openId = "";
      token = "";
      newPwd = "";
      oldPwd = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeString(1, this.openId);
      output.writeString(2, this.token);
      output.writeString(3, this.newPwd);
      if (!this.oldPwd.equals("")) {
        output.writeString(4, this.oldPwd);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.openId);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.token);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(3, this.newPwd);
      if (!this.oldPwd.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.oldPwd);
      }
      return size;
    }

    @Override
    public ReqSetPwd mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.openId = input.readString();
            break;
          }
          case 18: {
            this.token = input.readString();
            break;
          }
          case 26: {
            this.newPwd = input.readString();
            break;
          }
          case 34: {
            this.oldPwd = input.readString();
            break;
          }
        }
      }
    }

    public static ReqSetPwd parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ReqSetPwd(), data);
    }

    public static ReqSetPwd parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ReqSetPwd().mergeFrom(input);
    }
  }

  public static final class RspSetPwd extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RspSetPwd[] _emptyArray;
    public static RspSetPwd[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RspSetPwd[0];
          }
        }
      }
      return _emptyArray;
    }

    // required int32 rescode = 1;
    public int rescode;

    // required string resmsg = 2;
    public java.lang.String resmsg;

    // optional .AccountInfo account = 3;
    public UAC.AccountInfo account;

    public RspSetPwd() {
      clear();
    }

    public RspSetPwd clear() {
      rescode = 0;
      resmsg = "";
      account = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeInt32(1, this.rescode);
      output.writeString(2, this.resmsg);
      if (this.account != null) {
        output.writeMessage(3, this.account);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.rescode);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.resmsg);
      if (this.account != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.account);
      }
      return size;
    }

    @Override
    public RspSetPwd mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.rescode = input.readInt32();
            break;
          }
          case 18: {
            this.resmsg = input.readString();
            break;
          }
          case 26: {
            if (this.account == null) {
              this.account = new UAC.AccountInfo();
            }
            input.readMessage(this.account);
            break;
          }
        }
      }
    }

    public static RspSetPwd parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RspSetPwd(), data);
    }

    public static RspSetPwd parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RspSetPwd().mergeFrom(input);
    }
  }

  public static final class ReqThirdLogin extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ReqThirdLogin[] _emptyArray;
    public static ReqThirdLogin[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ReqThirdLogin[0];
          }
        }
      }
      return _emptyArray;
    }

    // required string thirdOpenId = 1;
    public java.lang.String thirdOpenId;

    // required string thirdType = 2;
    public java.lang.String thirdType;

    // optional string nickName = 3;
    public java.lang.String nickName;

    // optional string headImgUrl = 4;
    public java.lang.String headImgUrl;

    // optional int32 age = 5;
    public int age;

    // optional int32 gender = 6;
    public int gender;

    // optional int32 source = 7;
    public int source;

    public ReqThirdLogin() {
      clear();
    }

    public ReqThirdLogin clear() {
      thirdOpenId = "";
      thirdType = "";
      nickName = "";
      headImgUrl = "";
      age = 0;
      gender = 0;
      source = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeString(1, this.thirdOpenId);
      output.writeString(2, this.thirdType);
      if (!this.nickName.equals("")) {
        output.writeString(3, this.nickName);
      }
      if (!this.headImgUrl.equals("")) {
        output.writeString(4, this.headImgUrl);
      }
      if (this.age != 0) {
        output.writeInt32(5, this.age);
      }
      if (this.gender != 0) {
        output.writeInt32(6, this.gender);
      }
      if (this.source != 0) {
        output.writeInt32(7, this.source);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.thirdOpenId);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.thirdType);
      if (!this.nickName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.nickName);
      }
      if (!this.headImgUrl.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.headImgUrl);
      }
      if (this.age != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.age);
      }
      if (this.gender != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(6, this.gender);
      }
      if (this.source != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(7, this.source);
      }
      return size;
    }

    @Override
    public ReqThirdLogin mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.thirdOpenId = input.readString();
            break;
          }
          case 18: {
            this.thirdType = input.readString();
            break;
          }
          case 26: {
            this.nickName = input.readString();
            break;
          }
          case 34: {
            this.headImgUrl = input.readString();
            break;
          }
          case 40: {
            this.age = input.readInt32();
            break;
          }
          case 48: {
            this.gender = input.readInt32();
            break;
          }
          case 56: {
            this.source = input.readInt32();
            break;
          }
        }
      }
    }

    public static ReqThirdLogin parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ReqThirdLogin(), data);
    }

    public static ReqThirdLogin parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ReqThirdLogin().mergeFrom(input);
    }
  }

  public static final class RspThirdLogin extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RspThirdLogin[] _emptyArray;
    public static RspThirdLogin[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RspThirdLogin[0];
          }
        }
      }
      return _emptyArray;
    }

    // required int32 rescode = 1;
    public int rescode;

    // required string resmsg = 2;
    public java.lang.String resmsg;

    // optional .AccountInfo account = 3;
    public UAC.AccountInfo account;

    public RspThirdLogin() {
      clear();
    }

    public RspThirdLogin clear() {
      rescode = 0;
      resmsg = "";
      account = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeInt32(1, this.rescode);
      output.writeString(2, this.resmsg);
      if (this.account != null) {
        output.writeMessage(3, this.account);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.rescode);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.resmsg);
      if (this.account != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.account);
      }
      return size;
    }

    @Override
    public RspThirdLogin mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.rescode = input.readInt32();
            break;
          }
          case 18: {
            this.resmsg = input.readString();
            break;
          }
          case 26: {
            if (this.account == null) {
              this.account = new UAC.AccountInfo();
            }
            input.readMessage(this.account);
            break;
          }
        }
      }
    }

    public static RspThirdLogin parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RspThirdLogin(), data);
    }

    public static RspThirdLogin parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RspThirdLogin().mergeFrom(input);
    }
  }
}
