
package com.hykj.gamecenter.protocol;

// Generated by the protocol buffer compiler.  DO NOT EDIT!

@SuppressWarnings("hiding")
public interface Updater {

    public static final class ReqUpdate extends
            com.google.protobuf.nano.MessageNano {

        private static volatile ReqUpdate[] _emptyArray;

        public static ReqUpdate[] emptyArray() {
            // Lazily initializes the empty array
            if (_emptyArray == null) {
                synchronized (com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
                    if (_emptyArray == null) {
                        _emptyArray = new ReqUpdate[0];
                    }
                }
            }
            return _emptyArray;
        }

        // required string packName = 1;
        public java.lang.String packName;

        // required string verName = 2;
        public java.lang.String verName;

        // required int32 verCode = 3;
        public int verCode;

        public ReqUpdate() {
            clear();
        }

        public ReqUpdate clear() {
            packName = "";
            verName = "";
            verCode = 0;
            cachedSize = -1;
            return this;
        }

        @Override
        public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
                throws java.io.IOException {
            output.writeString(1, this.packName);
            output.writeString(2, this.verName);
            output.writeInt32(3, this.verCode);
            super.writeTo(output);
        }

        @Override
        protected int computeSerializedSize() {
            int size = super.computeSerializedSize();
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
                    .computeStringSize(1, this.packName);
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
                    .computeStringSize(2, this.verName);
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
                    .computeInt32Size(3, this.verCode);
            return size;
        }

        @Override
        public ReqUpdate mergeFrom(
                com.google.protobuf.nano.CodedInputByteBufferNano input)
                throws java.io.IOException {
            while (true) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        return this;
                    default: {
                        if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                            return this;
                        }
                        break;
                    }
                    case 10: {
                        this.packName = input.readString();
                        break;
                    }
                    case 18: {
                        this.verName = input.readString();
                        break;
                    }
                    case 24: {
                        this.verCode = input.readInt32();
                        break;
                    }
                }
            }
        }

        public static ReqUpdate parseFrom(byte[] data)
                throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
            return com.google.protobuf.nano.MessageNano.mergeFrom(new ReqUpdate(), data);
        }

        public static ReqUpdate parseFrom(
                com.google.protobuf.nano.CodedInputByteBufferNano input)
                throws java.io.IOException {
            return new ReqUpdate().mergeFrom(input);
        }
    }

    public static final class RspUpdate extends
            com.google.protobuf.nano.MessageNano {

        private static volatile RspUpdate[] _emptyArray;

        public static RspUpdate[] emptyArray() {
            // Lazily initializes the empty array
            if (_emptyArray == null) {
                synchronized (com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
                    if (_emptyArray == null) {
                        _emptyArray = new RspUpdate[0];
                    }
                }
            }
            return _emptyArray;
        }

        // required int32 rescode = 1;
        public int rescode;

        // required string resmsg = 2;
        public java.lang.String resmsg;

        // optional int32 updateType = 3;
        public int updateType;

        // optional string packName = 4;
        public java.lang.String packName;

        // optional string newVerName = 5;
        public java.lang.String newVerName;

        // optional int32 newVerCode = 6;
        public int newVerCode;

        // optional int32 packSize = 7;
        public int packSize;

        // optional string packMD5 = 8;
        public java.lang.String packMD5;

        // optional string packUrl = 9;
        public java.lang.String packUrl;

        // optional string pubTime = 10;
        public java.lang.String pubTime;

        // optional string updatePrompt = 11;
        public java.lang.String updatePrompt;

        // optional string updateDesc = 12;
        public java.lang.String updateDesc;

        public RspUpdate() {
            clear();
        }

        public RspUpdate clear() {
            rescode = 0;
            resmsg = "";
            updateType = 0;
            packName = "";
            newVerName = "";
            newVerCode = 0;
            packSize = 0;
            packMD5 = "";
            packUrl = "";
            pubTime = "";
            updatePrompt = "";
            updateDesc = "";
            cachedSize = -1;
            return this;
        }

        @Override
        public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
                throws java.io.IOException {
            output.writeInt32(1, this.rescode);
            output.writeString(2, this.resmsg);
            if (this.updateType != 0) {
                output.writeInt32(3, this.updateType);
            }
            if (!this.packName.equals("")) {
                output.writeString(4, this.packName);
            }
            if (!this.newVerName.equals("")) {
                output.writeString(5, this.newVerName);
            }
            if (this.newVerCode != 0) {
                output.writeInt32(6, this.newVerCode);
            }
            if (this.packSize != 0) {
                output.writeInt32(7, this.packSize);
            }
            if (!this.packMD5.equals("")) {
                output.writeString(8, this.packMD5);
            }
            if (!this.packUrl.equals("")) {
                output.writeString(9, this.packUrl);
            }
            if (!this.pubTime.equals("")) {
                output.writeString(10, this.pubTime);
            }
            if (!this.updatePrompt.equals("")) {
                output.writeString(11, this.updatePrompt);
            }
            if (!this.updateDesc.equals("")) {
                output.writeString(12, this.updateDesc);
            }
            super.writeTo(output);
        }

        @Override
        protected int computeSerializedSize() {
            int size = super.computeSerializedSize();
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
                    .computeInt32Size(1, this.rescode);
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
                    .computeStringSize(2, this.resmsg);
            if (this.updateType != 0) {
                size += com.google.protobuf.nano.CodedOutputByteBufferNano
                        .computeInt32Size(3, this.updateType);
            }
            if (!this.packName.equals("")) {
                size += com.google.protobuf.nano.CodedOutputByteBufferNano
                        .computeStringSize(4, this.packName);
            }
            if (!this.newVerName.equals("")) {
                size += com.google.protobuf.nano.CodedOutputByteBufferNano
                        .computeStringSize(5, this.newVerName);
            }
            if (this.newVerCode != 0) {
                size += com.google.protobuf.nano.CodedOutputByteBufferNano
                        .computeInt32Size(6, this.newVerCode);
            }
            if (this.packSize != 0) {
                size += com.google.protobuf.nano.CodedOutputByteBufferNano
                        .computeInt32Size(7, this.packSize);
            }
            if (!this.packMD5.equals("")) {
                size += com.google.protobuf.nano.CodedOutputByteBufferNano
                        .computeStringSize(8, this.packMD5);
            }
            if (!this.packUrl.equals("")) {
                size += com.google.protobuf.nano.CodedOutputByteBufferNano
                        .computeStringSize(9, this.packUrl);
            }
            if (!this.pubTime.equals("")) {
                size += com.google.protobuf.nano.CodedOutputByteBufferNano
                        .computeStringSize(10, this.pubTime);
            }
            if (!this.updatePrompt.equals("")) {
                size += com.google.protobuf.nano.CodedOutputByteBufferNano
                        .computeStringSize(11, this.updatePrompt);
            }
            if (!this.updateDesc.equals("")) {
                size += com.google.protobuf.nano.CodedOutputByteBufferNano
                        .computeStringSize(12, this.updateDesc);
            }
            return size;
        }

        @Override
        public RspUpdate mergeFrom(
                com.google.protobuf.nano.CodedInputByteBufferNano input)
                throws java.io.IOException {
            while (true) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        return this;
                    default: {
                        if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                            return this;
                        }
                        break;
                    }
                    case 8: {
                        this.rescode = input.readInt32();
                        break;
                    }
                    case 18: {
                        this.resmsg = input.readString();
                        break;
                    }
                    case 24: {
                        this.updateType = input.readInt32();
                        break;
                    }
                    case 34: {
                        this.packName = input.readString();
                        break;
                    }
                    case 42: {
                        this.newVerName = input.readString();
                        break;
                    }
                    case 48: {
                        this.newVerCode = input.readInt32();
                        break;
                    }
                    case 56: {
                        this.packSize = input.readInt32();
                        break;
                    }
                    case 66: {
                        this.packMD5 = input.readString();
                        break;
                    }
                    case 74: {
                        this.packUrl = input.readString();
                        break;
                    }
                    case 82: {
                        this.pubTime = input.readString();
                        break;
                    }
                    case 90: {
                        this.updatePrompt = input.readString();
                        break;
                    }
                    case 98: {
                        this.updateDesc = input.readString();
                        break;
                    }
                }
            }
        }

        public static RspUpdate parseFrom(byte[] data)
                throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
            return com.google.protobuf.nano.MessageNano.mergeFrom(new RspUpdate(), data);
        }

        public static RspUpdate parseFrom(
                com.google.protobuf.nano.CodedInputByteBufferNano input)
                throws java.io.IOException {
            return new RspUpdate().mergeFrom(input);
        }
    }
}
