# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Reported.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Reported.proto',
  package='',
  serialized_pb='\n\x0eReported.proto\"2\n\x0bReqReported\x12#\n\x0creportedInfo\x18\x01 \x03(\x0b\x32\r.ReportedInfo\"\x8f\x01\n\x0cReportedInfo\x12\x11\n\tstatActId\x18\x01 \x02(\x05\x12\x12\n\nstatActId2\x18\x02 \x01(\x05\x12\x12\n\nactionTime\x18\x03 \x01(\t\x12\x0c\n\x04\x65xt1\x18\x04 \x01(\t\x12\x0c\n\x04\x65xt2\x18\x05 \x01(\t\x12\x0c\n\x04\x65xt3\x18\x06 \x01(\t\x12\x0c\n\x04\x65xt4\x18\x07 \x01(\t\x12\x0c\n\x04\x65xt5\x18\x08 \x01(\t\".\n\x0bRspReported\x12\x0f\n\x07rescode\x18\x01 \x02(\x05\x12\x0e\n\x06resmsg\x18\x02 \x02(\t')




_REQREPORTED = _descriptor.Descriptor(
  name='ReqReported',
  full_name='ReqReported',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reportedInfo', full_name='ReqReported.reportedInfo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=68,
)


_REPORTEDINFO = _descriptor.Descriptor(
  name='ReportedInfo',
  full_name='ReportedInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statActId', full_name='ReportedInfo.statActId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='statActId2', full_name='ReportedInfo.statActId2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actionTime', full_name='ReportedInfo.actionTime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ext1', full_name='ReportedInfo.ext1', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ext2', full_name='ReportedInfo.ext2', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ext3', full_name='ReportedInfo.ext3', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ext4', full_name='ReportedInfo.ext4', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ext5', full_name='ReportedInfo.ext5', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=71,
  serialized_end=214,
)


_RSPREPORTED = _descriptor.Descriptor(
  name='RspReported',
  full_name='RspReported',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rescode', full_name='RspReported.rescode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resmsg', full_name='RspReported.resmsg', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=216,
  serialized_end=262,
)

_REQREPORTED.fields_by_name['reportedInfo'].message_type = _REPORTEDINFO
DESCRIPTOR.message_types_by_name['ReqReported'] = _REQREPORTED
DESCRIPTOR.message_types_by_name['ReportedInfo'] = _REPORTEDINFO
DESCRIPTOR.message_types_by_name['RspReported'] = _RSPREPORTED

class ReqReported(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQREPORTED

  # @@protoc_insertion_point(class_scope:ReqReported)

class ReportedInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REPORTEDINFO

  # @@protoc_insertion_point(class_scope:ReportedInfo)

class RspReported(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RSPREPORTED

  # @@protoc_insertion_point(class_scope:RspReported)


# @@protoc_insertion_point(module_scope)
