package com.reportforms.dao;

import com.reportforms.model.Region;
import com.reportforms.model.RegionExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RegionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_region
	 * @mbggenerated  Mon Jul 29 11:10:22 CST 2013
	 */
	int countByExample(RegionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_region
	 * @mbggenerated  Mon Jul 29 11:10:22 CST 2013
	 */
	int deleteByExample(RegionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_region
	 * @mbggenerated  Mon Jul 29 11:10:22 CST 2013
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_region
	 * @mbggenerated  Mon Jul 29 11:10:22 CST 2013
	 */
	int insert(Region record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_region
	 * @mbggenerated  Mon Jul 29 11:10:22 CST 2013
	 */
	int insertSelective(Region record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_region
	 * @mbggenerated  Mon Jul 29 11:10:22 CST 2013
	 */
	List<Region> selectByExample(RegionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_region
	 * @mbggenerated  Mon Jul 29 11:10:22 CST 2013
	 */
	Region selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_region
	 * @mbggenerated  Mon Jul 29 11:10:22 CST 2013
	 */
	int updateByExampleSelective(@Param("record") Region record,
			@Param("example") RegionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_region
	 * @mbggenerated  Mon Jul 29 11:10:22 CST 2013
	 */
	int updateByExample(@Param("record") Region record,
			@Param("example") RegionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_region
	 * @mbggenerated  Mon Jul 29 11:10:22 CST 2013
	 */
	int updateByPrimaryKeySelective(Region record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_region
	 * @mbggenerated  Mon Jul 29 11:10:22 CST 2013
	 */
	int updateByPrimaryKey(Region record);

	List<Region> selectByExample(RegionExample example, RowBounds rowBounds);
}