package com.reportforms.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.reportforms.model.RoleMenu;
import com.reportforms.model.RoleMenuExample;

public interface RoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbggenerated Wed Dec 21 09:30:49 CST 2011
     */
    int countByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbggenerated Wed Dec 21 09:30:49 CST 2011
     */
    int deleteByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbggenerated Wed Dec 21 09:30:49 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbggenerated Wed Dec 21 09:30:49 CST 2011
     */
    int insert(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbggenerated Wed Dec 21 09:30:49 CST 2011
     */
    int insertSelective(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbggenerated Wed Dec 21 09:30:49 CST 2011
     */
    List<RoleMenu> selectByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbggenerated Wed Dec 21 09:30:49 CST 2011
     */
    RoleMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbggenerated Wed Dec 21 09:30:49 CST 2011
     */
    int updateByExampleSelective(@Param("record") RoleMenu record, @Param("example") RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbggenerated Wed Dec 21 09:30:49 CST 2011
     */
    int updateByExample(@Param("record") RoleMenu record, @Param("example") RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbggenerated Wed Dec 21 09:30:49 CST 2011
     */
    int updateByPrimaryKeySelective(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbggenerated Wed Dec 21 09:30:49 CST 2011
     */
    int updateByPrimaryKey(RoleMenu record);
}