package com.mas.rave.main.vo;

import java.util.ArrayList;
import java.util.List;

public class AppAlbumThemeExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table t_menu
	 * 
	 * @mbggenerated Fri Dec 23 08:44:42 CST 2011
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table t_menu
	 * 
	 * @mbggenerated Fri Dec 23 08:44:42 CST 2011
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table t_menu
	 * 
	 * @mbggenerated Fri Dec 23 08:44:42 CST 2011
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_menu
	 * 
	 * @mbggenerated Fri Dec 23 08:44:42 CST 2011
	 */
	public AppAlbumThemeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_menu
	 * 
	 * @mbggenerated Fri Dec 23 08:44:42 CST 2011
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_menu
	 * 
	 * @mbggenerated Fri Dec 23 08:44:42 CST 2011
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_menu
	 * 
	 * @mbggenerated Fri Dec 23 08:44:42 CST 2011
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_menu
	 * 
	 * @mbggenerated Fri Dec 23 08:44:42 CST 2011
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_menu
	 * 
	 * @mbggenerated Fri Dec 23 08:44:42 CST 2011
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_menu
	 * 
	 * @mbggenerated Fri Dec 23 08:44:42 CST 2011
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_menu
	 * 
	 * @mbggenerated Fri Dec 23 08:44:42 CST 2011
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_menu
	 * 
	 * @mbggenerated Fri Dec 23 08:44:42 CST 2011
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_menu
	 * 
	 * @mbggenerated Fri Dec 23 08:44:42 CST 2011
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_menu
	 * 
	 * @mbggenerated Fri Dec 23 08:44:42 CST 2011
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterion(String condition, Object value1, String property, Object value2) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("and values for " + property + condition + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, property, value2));
		}

		public Criteria andApkIdEqualTo(Integer value) {
			addCriterion("apkId =", value, "apkId");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", "%" + value + "%", "name");
			return (Criteria) this;
		}

		public Criteria andAppAlbumColumnIdEqualTo(int appAlbumColumnId) {
			addCriterion("columnId=", appAlbumColumnId, "columnId");
			return (Criteria) this;
		}

		public Criteria andFlag(int flag) {
			if (flag == 1) {
				addCriterion("flag !=", 3, "flag");
			} else {
				addCriterion("flag =", flag, "flag");
			}
			return (Criteria) this;
		}

		public Criteria andAppAlbumEqualTo(int[] appAlbumColumnIds) {
			StringBuilder sb = new StringBuilder("(");
			for (int i = 0; i < appAlbumColumnIds.length; i++) {
				sb.append(appAlbumColumnIds[i]).append(",");
			}
			sb.delete(sb.length() - 1, sb.length());
			sb.append(")");
			addCriterion("columnId in" + sb.toString());
			return (Criteria) this;
		}

		public Criteria andRaveIdEqual(Integer value) {
			addCriterion("raveId =", value, "raveId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table t_menu
	 * 
	 * @mbggenerated do_not_delete_during_merge Fri Dec 23 08:44:42 CST 2011
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table t_menu
	 * 
	 * @mbggenerated Fri Dec 23 08:44:42 CST 2011
	 */
	public static class Criterion {
		private String condition;

		private String secondCondition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean andValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public String getSecondCondition() {
			return secondCondition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isAndValue() {
			return andValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String secondCondition, String typeHandler) {
			super();
			this.condition = condition;
			this.secondCondition = secondCondition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.andValue = true;
		}

		protected Criterion(String condition, Object value, String secondCondition, Object secondValue) {
			this(condition, value, secondValue, secondCondition, null);
		}

	}
}