package com.reportforms.model;

import java.util.List;

public class Region {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_region.id
	 * @mbggenerated  Mon Jul 29 11:10:22 CST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_region.name
	 * @mbggenerated  Mon Jul 29 11:10:22 CST 2013
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_region.remark
	 * @mbggenerated  Mon Jul 29 11:10:22 CST 2013
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_region.id
	 * @return  the value of t_region.id
	 * @mbggenerated  Mon Jul 29 11:10:22 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_region.id
	 * @param id  the value for t_region.id
	 * @mbggenerated  Mon Jul 29 11:10:22 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_region.name
	 * @return  the value of t_region.name
	 * @mbggenerated  Mon Jul 29 11:10:22 CST 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_region.name
	 * @param name  the value for t_region.name
	 * @mbggenerated  Mon Jul 29 11:10:22 CST 2013
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_region.remark
	 * @return  the value of t_region.remark
	 * @mbggenerated  Mon Jul 29 11:10:22 CST 2013
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_region.remark
	 * @param remark  the value for t_region.remark
	 * @mbggenerated  Mon Jul 29 11:10:22 CST 2013
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	private List<Country> listCountry;

	public List<Country> getListCountry() {
		return listCountry;
	}

	public void setListCountry(List<Country> listCountry) {
		this.listCountry = listCountry;
	}
	
	
}